openapi: 3.0.1
info:
  title: Aws Sam Pip
  description: ""
  x-cortex-tag: aws_sam-pip
  x-cortex-git:
    github:
      repository: cortex-demo/AWS_SAM-pip
  x-cortex-custom-metadata:
    cortex-template-version: 1.0
    cortex-generated-timestamp: 2023-08-28T14:28:37.549307655
